In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import importlib

scripts_path = os.path.abspath("../scripts")
print(scripts_path)
print(os.listdir(scripts_path))

sys.path.insert(0, scripts_path)

import preprocessing
importlib.reload(preprocessing)

from preprocessing import preprocess_lake_storage

print("Import successful!")

/Users/anuthakur/code/DaveGiGi/Duckstradamus/notebooks/duckstradamus_preprocessing/scripts
['__pycache__', 'preprocessing.py']
Import successful!

In [2]:
# load data
file_path = "../dataset/Lakes storage levels/NI_TPO_Storage_LakeTaupo.csv"

lake_storage = pd.read_csv(file_path)
lake_storage.head()

,Date,Time,Lake level (m),Active storage (Mm³),Active contingent storage (Mm³),QualityCode
0,1980-03-18,23:59:59,356.790,574.629,NaN,320.0
1,1980-06-16,23:59:59,356.982,692.061,NaN,320.0
2,1980-10-09,23:59:59,356.968,683.315,NaN,320.0
3,1981-02-05,23:59:59,356.756,554.143,NaN,320.0
4,1981-06-06,23:59:59,356.302,276.657,NaN,320.0

In [3]:
# basic inspection
lake_storage.info()
lake_storage.isnull().sum()
lake_storage.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16438 entries, 0 to 16437
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Date                             16437 non-null  object
 1   Time                             16438 non-null  object
 2   Lake level (m)                   16437 non-null  float64
 3   Active storage (Mm³)             16437 non-null  float64
 4   Active contingent storage (Mm³)  0 non-null      float64
 5   QualityCode                      16437 non-null  float64
dtypes: float64(4), object(2)
memory usage: 770.7+ KB

0

In [4]:
# clean the data columns
lake_storage.columns = (
    lake_storage.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

lake_storage.columns

Index(['date', 'time', 'lake_level_m', 'active_storage_mm³',
       'active_contingent_storage_mm³', 'qualitycode'],
      dtype='object')

In [5]:
# create datetime column
lake_storage["datetime"] = pd.to_datetime(
    lake_storage["date"] + " " + lake_storage["time"],
    errors="coerce"
)

In [6]:
# keep only useful columns
lake_storage = lake_storage[
    ["datetime", "lake_level_m", "active_storage_mm³"]
]

In [7]:
# drop missing values
lake_storage.dropna(inplace=True)

In [8]:
# remove duplicates
lake_storage.drop_duplicates(inplace=True)

In [9]:
# sort by the datetime
lake_storage = lake_storage.sort_values("datetime")

In [10]:
# reset index
lake_storage.reset_index(drop=True, inplace=True)

In [11]:
# final check
lake_storage.info()
lake_storage.head()
lake_storage.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16437 entries, 0 to 16436
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            16437 non-null  datetime64[ns]
 1   lake_level_m        16437 non-null  float64
 2   active_storage_mm³  16437 non-null  float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 385.4 KB

datetime              0
lake_level_m          0
active_storage_mm³    0
dtype: int64

In [12]:
lake_storage.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       357.101             764.657
1 1980-01-02 23:59:59       357.102             765.245
2 1980-01-03 23:59:59       357.086             755.718
3 1980-01-04 23:59:59       357.062             741.110
4 1980-01-05 23:59:59       357.052             734.750

In [13]:
lake_taupo = preprocess_lake_storage(
    "../dataset/Lakes storage levels/NI_TPO_Storage_LakeTaupo.csv"
)

lake_taupo.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       357.101             764.657
1 1980-01-02 23:59:59       357.102             765.245
2 1980-01-03 23:59:59       357.086             755.718
3 1980-01-04 23:59:59       357.062             741.110
4 1980-01-05 23:59:59       357.052             734.750

In [14]:
lake_waikaremoana = preprocess_lake_storage(
    "../dataset/Lakes storage levels/NI_WKA_Storage_LakeWaikaremoana.csv"
)

lake_waikaremoana.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       582.976             141.024
1 1980-01-02 23:59:59       583.017             143.173
2 1980-01-03 23:59:59       582.998             142.175
3 1980-01-04 23:59:59       582.984             141.443
4 1980-01-05 23:59:59       583.024             143.538

In [15]:
lake_hawea = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_HWE_Storage_LakeHawea.csv"
)

lake_hawea.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       345.840            2134.608
1 1980-01-02 23:59:59       345.893            2142.492
2 1980-01-03 23:59:59       345.962            2152.809
3 1980-01-04 23:59:59       346.005            2159.318
4 1980-01-05 23:59:59       346.046            2165.419

In [16]:
lake_manapouri = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_MAN_Storage_LakeManapouri.csv"
)

lake_manapouri.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       178.631             384.398
1 1980-01-02 23:59:59       178.554             373.734
2 1980-01-03 23:59:59       178.465             361.322
3 1980-01-04 23:59:59       178.330             342.446
4 1980-01-05 23:59:59       178.197             323.942

In [17]:
lake_ohau = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_OHA_Storage_LakeOhau.csv"
)

lake_ohau.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       520.117              41.403
1 1980-01-02 23:59:59       520.117              41.403
2 1980-01-03 23:59:59       520.100              40.355
3 1980-01-04 23:59:59       520.023              35.560
4 1980-01-05 23:59:59       519.938              30.281

In [18]:
lake_pukaki = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_PKI_Storage_LakePukaki.csv"
)

lake_pukaki.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       532.535            2433.618
1 1980-01-02 23:59:59       532.548            2433.618
2 1980-01-03 23:59:59       532.594            2441.836
3 1980-01-04 23:59:59       532.579            2439.131
4 1980-01-05 23:59:59       532.557            2435.212

In [19]:
lake_teanau = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_TAU_Storage_LakeTeAnau.csv"
)

lake_teanau.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       203.214             828.373
1 1980-01-02 23:59:59       203.225             832.036
2 1980-01-03 23:59:59       203.244             839.002
3 1980-01-04 23:59:59       203.262             845.125
4 1980-01-05 23:59:59       203.267             846.892

In [20]:
lake_tekapo = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_TKA_Storage_LakeTekapo.csv"
)

lake_tekapo.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       711.323             674.757
1 1980-01-02 23:59:59       711.323             674.757
2 1980-01-03 23:59:59       711.293             671.748
3 1980-01-04 23:59:59       711.214             663.794
4 1980-01-05 23:59:59       711.119             654.281

In [21]:
lake_wanaka = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_WAN_Storage_LakeWanaka.csv"
)

lake_wanaka.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       278.201             540.791
1 1980-01-02 23:59:59       278.151             531.143
2 1980-01-03 23:59:59       278.113             523.810
3 1980-01-04 23:59:59       278.045             510.688
4 1980-01-05 23:59:59       277.975             497.176

In [22]:
lake_wakatipu = preprocess_lake_storage(
    "../dataset/Lakes storage levels/SI_WPU_Storage_LakeWakatipu.csv"
)

lake_wakatipu.head()

             datetime  lake_level_m  active_storage_mm³
0 1980-01-01 23:59:59       310.524             489.578
1 1980-01-02 23:59:59       310.504             483.661
2 1980-01-03 23:59:59       310.481             477.056
3 1980-01-04 23:59:59       310.445             466.722
4 1980-01-05 23:59:59       310.415             458.020

In [23]:
# =========================
# SAVE CLEANED FILES
# =========================

from pathlib import Path

# create cleaned_data folder if it doesn't exist
output_folder = Path("../cleaned_data")
output_folder.mkdir(exist_ok=True)

# dictionary of all lakes
lake_files = {
    "lake_taupo": "../dataset/Lakes storage levels/NI_TPO_Storage_LakeTaupo.csv",
    "lake_waikaremoana": "../dataset/Lakes storage levels/NI_WKA_Storage_LakeWaikaremoana.csv",
    "lake_hawea": "../dataset/Lakes storage levels/SI_HWE_Storage_LakeHawea.csv",
    "lake_manapouri": "../dataset/Lakes storage levels/SI_MAN_Storage_LakeManapouri.csv",
    "lake_ohau": "../dataset/Lakes storage levels/SI_OHA_Storage_LakeOhau.csv",
    "lake_pukaki": "../dataset/Lakes storage levels/SI_PKI_Storage_LakePukaki.csv",
    "lake_teanau": "../dataset/Lakes storage levels/SI_TAU_Storage_LakeTeAnau.csv",
    "lake_tekapo": "../dataset/Lakes storage levels/SI_TKA_Storage_LakeTekapo.csv",
    "lake_wanaka": "../dataset/Lakes storage levels/SI_WAN_Storage_LakeWanaka.csv",
    "lake_wakatipu": "../dataset/Lakes storage levels/SI_WPU_Storage_LakeWakatipu.csv",
}

# store cleaned dfs
cleaned_lakes = {}

# loop through all files
for lake_name, file_path in lake_files.items():

    # preprocess
    df = preprocess_lake_storage(file_path)

    # store dataframe
    cleaned_lakes[lake_name] = df

    # save cleaned csv
    save_path = output_folder / f"{lake_name}_cleaned.csv"

    df.to_csv(save_path, index=False)

    print(f"✅ Saved successfully: {save_path}")

print("\n🎉 All lake files cleaned and saved!")

✅ Saved successfully: ../cleaned_data/lake_taupo_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_waikaremoana_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_hawea_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_manapouri_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_ohau_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_pukaki_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_teanau_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_tekapo_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_wanaka_cleaned.csv
✅ Saved successfully: ../cleaned_data/lake_wakatipu_cleaned.csv

🎉 All lake files cleaned and saved!

In [24]:
solar = pd.read_csv("../dataset/Solar_data.csv")

solar.head()

,time,Auckland_shortwave_wm2,Auckland_sunshine_s,Christchurch_shortwave_wm2,Christchurch_sunshine_s,Wellington_shortwave_wm2,Wellington_sunshine_s,Hamilton_shortwave_wm2,Hamilton_sunshine_s,Tauranga_shortwave_wm2,Tauranga_sunshine_s,Dunedin_shortwave_wm2,Dunedin_sunshine_s
0,2014-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
solar.info()
solar.shape
solar.isnull().sum()
solar.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108672 entries, 0 to 108671
Data columns (total 13 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   time                        108672 non-null  object
 1   Auckland_shortwave_wm2      108672 non-null  float64
 2   Auckland_sunshine_s         108672 non-null  float64
 3   Christchurch_shortwave_wm2  108672 non-null  float64
 4   Christchurch_sunshine_s     108672 non-null  float64
 5   Wellington_shortwave_wm2    108672 non-null  float64
 6   Wellington_sunshine_s       108672 non-null  float64
 7   Hamilton_shortwave_wm2      108672 non-null  float64
 8   Hamilton_sunshine_s         108672 non-null  float64
 9   Tauranga_shortwave_wm2      108672 non-null  float64
 10  Tauranga_sunshine_s         108672 non-null  float64
 11  Dunedin_shortwave_wm2       108672 non-null  float64
 12  Dunedin_sunshine_s          108672 non-null  float64
dtypes: float64(12), object(1)
memory usage: 10.8+ MB

0

In [26]:
solar.columns = (
    solar.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

solar.columns

Index(['time', 'auckland_shortwave_wm2', 'auckland_sunshine_s',
       'christchurch_shortwave_wm2', 'christchurch_sunshine_s',
       'wellington_shortwave_wm2', 'wellington_sunshine_s',
       'hamilton_shortwave_wm2', 'hamilton_sunshine_s',
       'tauranga_shortwave_wm2', 'tauranga_sunshine_s',
       'dunedin_shortwave_wm2', 'dunedin_sunshine_s'],
      dtype='object')

In [27]:
solar["datetime"] = pd.to_datetime(
    solar["time"],
    errors="coerce"
)

solar.head()

,time,auckland_shortwave_wm2,auckland_sunshine_s,christchurch_shortwave_wm2,christchurch_sunshine_s,wellington_shortwave_wm2,wellington_sunshine_s,hamilton_shortwave_wm2,hamilton_sunshine_s,tauranga_shortwave_wm2,tauranga_sunshine_s,dunedin_shortwave_wm2,dunedin_sunshine_s,datetime
0,2014-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-01-01 00:00:00
1,2014-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-01-01 01:00:00
2,2014-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-01-01 02:00:00
3,2014-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-01-01 03:00:00
4,2014-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-01-01 04:00:00

In [28]:
solar.drop(columns=["time"], inplace=True)

In [29]:
solar = solar[
    ["datetime"] + [col for col in solar.columns if col != "datetime"]
]

solar.head()

,datetime,auckland_shortwave_wm2,auckland_sunshine_s,christchurch_shortwave_wm2,christchurch_sunshine_s,wellington_shortwave_wm2,wellington_sunshine_s,hamilton_shortwave_wm2,hamilton_sunshine_s,tauranga_shortwave_wm2,tauranga_sunshine_s,dunedin_shortwave_wm2,dunedin_sunshine_s
0,2014-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
solar.dropna(inplace=True)

In [31]:
solar.drop_duplicates(inplace=True)

In [32]:
solar = solar.sort_values("datetime")

In [33]:
solar.reset_index(drop=True, inplace=True)

In [34]:
solar.info()
solar.head()
solar.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108672 entries, 0 to 108671
Data columns (total 13 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   datetime                    108672 non-null  datetime64[ns]
 1   auckland_shortwave_wm2      108672 non-null  float64
 2   auckland_sunshine_s         108672 non-null  float64
 3   christchurch_shortwave_wm2  108672 non-null  float64
 4   christchurch_sunshine_s     108672 non-null  float64
 5   wellington_shortwave_wm2    108672 non-null  float64
 6   wellington_sunshine_s       108672 non-null  float64
 7   hamilton_shortwave_wm2      108672 non-null  float64
 8   hamilton_sunshine_s         108672 non-null  float64
 9   tauranga_shortwave_wm2      108672 non-null  float64
 10  tauranga_sunshine_s         108672 non-null  float64
 11  dunedin_shortwave_wm2       108672 non-null  float64
 12  dunedin_sunshine_s          108672 non-null  float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 10.8 MB

datetime                      0
auckland_shortwave_wm2        0
auckland_sunshine_s           0
christchurch_shortwave_wm2    0
christchurch_sunshine_s       0
wellington_shortwave_wm2      0
wellington_sunshine_s         0
hamilton_shortwave_wm2        0
hamilton_sunshine_s           0
tauranga_shortwave_wm2        0
tauranga_sunshine_s           0
dunedin_shortwave_wm2         0
dunedin_sunshine_s            0
dtype: int64

In [35]:
from preprocessing import preprocess_solar_data

In [36]:
solar = preprocess_solar_data(
    "../dataset/Solar_data.csv"
)

solar.head()

,datetime,auckland_shortwave_wm2,auckland_sunshine_s,christchurch_shortwave_wm2,christchurch_sunshine_s,wellington_shortwave_wm2,wellington_sunshine_s,hamilton_shortwave_wm2,hamilton_sunshine_s,tauranga_shortwave_wm2,tauranga_sunshine_s,dunedin_shortwave_wm2,dunedin_sunshine_s
0,2014-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
solar.to_csv(
    "../cleaned_data/solar_cleaned.csv",
    index=False
)

In [40]:
temperature = pd.read_csv("../dataset/Temperature_data.csv")
temperature.head()

,time,Auckland_temp_c,Christchurch_temp_c,Wellington_temp_c,Hamilton_temp_c,Tauranga_temp_c,Dunedin_temp_c
0,2014-01-01 00:00:00,16.6,11.9,15.8,11.7,14.2,11.1
1,2014-01-01 01:00:00,15.9,11.2,15.8,13.3,13.7,10.2
2,2014-01-01 02:00:00,14.6,10.5,15.8,12.4,13.0,9.6
3,2014-01-01 03:00:00,14.5,10.0,15.8,9.5,12.2,9.0
4,2014-01-01 04:00:00,13.7,9.9,15.7,8.8,13.5,8.8

In [41]:
temperature.info()
temperature.isnull().sum()
temperature.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108672 entries, 0 to 108671
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   time                 108672 non-null  object
 1   Auckland_temp_c      108672 non-null  float64
 2   Christchurch_temp_c  108672 non-null  float64
 3   Wellington_temp_c    108672 non-null  float64
 4   Hamilton_temp_c      108672 non-null  float64
 5   Tauranga_temp_c      108672 non-null  float64
 6   Dunedin_temp_c       108672 non-null  float64
dtypes: float64(6), object(1)
memory usage: 5.8+ MB

0

In [42]:
temperature.columns = (
    temperature.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

temperature.columns

Index(['time', 'auckland_temp_c', 'christchurch_temp_c', 'wellington_temp_c',
       'hamilton_temp_c', 'tauranga_temp_c', 'dunedin_temp_c'],
      dtype='object')

In [43]:
temperature["datetime"] = pd.to_datetime(
    temperature["time"],
    errors="coerce"
)

temperature.head()

,time,auckland_temp_c,christchurch_temp_c,wellington_temp_c,hamilton_temp_c,tauranga_temp_c,dunedin_temp_c,datetime
0,2014-01-01 00:00:00,16.6,11.9,15.8,11.7,14.2,11.1,2014-01-01 00:00:00
1,2014-01-01 01:00:00,15.9,11.2,15.8,13.3,13.7,10.2,2014-01-01 01:00:00
2,2014-01-01 02:00:00,14.6,10.5,15.8,12.4,13.0,9.6,2014-01-01 02:00:00
3,2014-01-01 03:00:00,14.5,10.0,15.8,9.5,12.2,9.0,2014-01-01 03:00:00
4,2014-01-01 04:00:00,13.7,9.9,15.7,8.8,13.5,8.8,2014-01-01 04:00:00

In [44]:
temperature.drop(columns=["time"], inplace=True)

In [45]:
temperature = temperature[
    ["datetime"] + [col for col in temperature.columns if col != "datetime"]
]

temperature.head()

,datetime,auckland_temp_c,christchurch_temp_c,wellington_temp_c,hamilton_temp_c,tauranga_temp_c,dunedin_temp_c
0,2014-01-01 00:00:00,16.6,11.9,15.8,11.7,14.2,11.1
1,2014-01-01 01:00:00,15.9,11.2,15.8,13.3,13.7,10.2
2,2014-01-01 02:00:00,14.6,10.5,15.8,12.4,13.0,9.6
3,2014-01-01 03:00:00,14.5,10.0,15.8,9.5,12.2,9.0
4,2014-01-01 04:00:00,13.7,9.9,15.7,8.8,13.5,8.8

In [46]:
temperature.dropna(inplace=True)

In [47]:
temperature = temperature.sort_values("datetime")

In [48]:
temperature.reset_index(drop=True, inplace=True)

In [49]:
temperature.info()
temperature.head()
temperature.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108672 entries, 0 to 108671
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   datetime             108672 non-null  datetime64[ns]
 1   auckland_temp_c      108672 non-null  float64
 2   christchurch_temp_c  108672 non-null  float64
 3   wellington_temp_c    108672 non-null  float64
 4   hamilton_temp_c      108672 non-null  float64
 5   tauranga_temp_c      108672 non-null  float64
 6   dunedin_temp_c       108672 non-null  float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 5.8 MB

datetime               0
auckland_temp_c        0
christchurch_temp_c    0
wellington_temp_c      0
hamilton_temp_c        0
tauranga_temp_c        0
dunedin_temp_c         0
dtype: int64

In [50]:
import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import preprocess_temperature_data

In [51]:
temperature = preprocess_temperature_data(
    "../dataset/Temperature_data.csv"
)

temperature.head()

,datetime,auckland_temp_c,christchurch_temp_c,wellington_temp_c,hamilton_temp_c,tauranga_temp_c,dunedin_temp_c
0,2014-01-01 00:00:00,16.6,11.9,15.8,11.7,14.2,11.1
1,2014-01-01 01:00:00,15.9,11.2,15.8,13.3,13.7,10.2
2,2014-01-01 02:00:00,14.6,10.5,15.8,12.4,13.0,9.6
3,2014-01-01 03:00:00,14.5,10.0,15.8,9.5,12.2,9.0
4,2014-01-01 04:00:00,13.7,9.9,15.7,8.8,13.5,8.8

In [52]:
temperature.to_csv(
    "../cleaned_data/temperature_cleaned.csv",
    index=False
)

In [53]:
import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import preprocess_wind_data

In [54]:
wind = preprocess_wind_data(
    "../dataset/Wind_data_100m.csv"
)

wind.head()

,datetime,palmerston_north_wind_kmh,palmerston_north_wind_dir_deg,wellington_wind_kmh,wellington_wind_dir_deg,harapaki_hawkesbay_wind_kmh,harapaki_hawkesbay_wind_dir_deg,te_uku_waikato_wind_kmh,te_uku_waikato_wind_dir_deg,kaiwera_downs_southland_wind_kmh,kaiwera_downs_southland_wind_dir_deg
0,2014-01-01 00:00:00,20.2,325,36.9,324,4.5,346,12.8,286,4.4,279
1,2014-01-01 01:00:00,20.9,336,36.3,323,5.9,317,8.6,285,1.5,284
2,2014-01-01 02:00:00,22.5,347,35.7,326,7.6,301,4.3,312,1.5,284
3,2014-01-01 03:00:00,23.1,355,36.3,328,8.5,298,5.6,345,1.1,72
4,2014-01-01 04:00:00,23.0,360,35.9,329,8.9,291,6.5,360,4.3,85

In [55]:
wind.to_csv(
    "../cleaned_data/wind_cleaned.csv",
    index=False
)